// <auto-generated />
namespace Stipendium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Stiftelse_Dates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stiftelse_Dates));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041355074_Stiftelse_Dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
