// <auto-generated />
namespace Stipendium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CompanyVModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompanyVModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201808301356419_CompanyVModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
