// <auto-generated />
namespace Stipendium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LastModified_2_Stiftelse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastModified_2_Stiftelse));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041340539_LastModified_2_Stiftelse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
